[project]
name = "dora-based-nana-teleop-ws"
version = "0.1.0"
description = "Workspace for Dora-based NANA v3 VR Teleoperation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dora-rs>=0.5.0",
    "dora-rs-cli>=0.5.0",
    "dora-openarm-vr",
    "dora-openarm-kinematics",
    "dora-openarm-kinematics-control",
    "dora-openarm-mujoco",
    "dora-openarm-quitter",
    "dora-openarm",
    "openarm-driver",
    "hamsa_driver",
]

[tool.uv.workspace]
members = [
    "src/nana_v3_dora_teleop_vr/dora-openarm-vr",
    "src/nana_v3_dora_teleop_vr/dora-openarm-kinematics",
    "src/nana_v3_dora_teleop_vr/dora-openarm-kinematics-control",
    "src/nana_v3_dora_teleop_vr/dora-openarm-mujoco",
    "src/nana_v3_dora_teleop_vr/dora-openarm-quitter",
    "src/nana_v3_dora_teleop_vr/dora-openarm",
    "src/utils/openarm_driver",
    "src/utils/hamsa_driver",
]

[tool.uv.sources]
dora-openarm-vr = { workspace = true }
dora-openarm-kinematics = { workspace = true }
dora-openarm-kinematics-control = { workspace = true }
dora-openarm-mujoco = { workspace = true }
dora-openarm-quitter = { workspace = true }
dora-openarm = { workspace = true }
openarm-driver = { workspace = true }
hamsa_driver = { workspace = true }
